### ISSUE TITLE
[SHOWER THOUGHT] Optimize for newer uarchs

### ISSUE THREAD

**Issue by jrelvas-ipc** [vinegarhq/wine-builds#1]
ok so hear me out

Roblox doesn't run without AVX support.

These builds are tailor-made for Roblox.

What if... we build with AVX instructions? There's no loss since users who can't run these builds wouldn't be able to run Roblox anyways, and there might be minor performance improvements :)

~~Just need to clarify if AVX is enough or if AVX2 was also required.~~
AVX is the minimum requirement.

If `AVX` is the requirement...
- ~~Build for `x86-64-v2` plus `avx`.~~
- Build for [Sandy Bridge](https://en.wikipedia.org/wiki/Sandy_Bridge) featureset.

~~if `AVX2` is the requirement...~~
- ~~Build for `x86-64-v3`.~~

This should squeeze out slight optimizations for Wine, while still being compatible with all existing users.

**Comment by apprehensions** [comment]
implemented in 64901cf35d37267207793b480ab7424a66684843
